version: '2.4'
services:
  backend:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    # env_file:
    #   - ./.env
    depends_on:
      - mongodb
  # frontend:
  #   image: "redis:alpine"
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    command: mongod --quiet --logpath /dev/null
    # env_file:
    #   - ./backend/.env
volumes:
  data:
